name: Run JMeter Test using PerfAction

on: [push]

jobs:
  run-jmeter:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: List Directory for Debugging
        run: ls -R

      - name: PerfAction for JMeter
        uses: QAInsights/PerfAction@v5.6.3
        with:
          test-plan-path: './BlazeDemo_June_11.jmx'
          results-file-path: 'results.jtl'  # ✅ Corrected key
          args: '-Jthreads=10 -Jduration=60'

      - name: Upload JMeter Results
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-results
          path: results.jtl
